extract_data:
  description: >
    Trích xuất dữ liệu cần thiết cho truy vấn: {query}
  expected_output: >
    Kết quả cơ sở dữ liệu cho truy vấn.
  agent: sql_dev

analyze_data:
  description: >
    Phân tích dữ liệu từ cơ sở dữ liệu và viết phân tích cho: {query}
  expected_output: >
    Văn bản phân tích chi tiết.
  agent: data_analyst
  context: [extract_data]

write_report:
  description: >
    Viết bản tóm tắt phân tích trong vòng chưa đầy 100 từ.
  expected_output: >
    Báo cáo giảm giá
  agent: report_writer
  context: [analyze_data]